name: Downloading repo in runner machine

on: [push]

jobs:
    Checkout:
        runs-on: ubuntu-latest
        steps:
          - name: List files before
            run: ls -a
          - name: Checkout
            run: |
              git init
              git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
              git branch -M main
              git pull
          - name: List files after
            run: ls -a