name: Dynamic Matrix

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: Node Verison
        default: "14,15,16"
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-arrays: ${{ steps.matrix-arrays.outputs.result}}
    steps:
      - uses: actions/github-script@v6
        id: matrix-arrays
        with:
          script: "return {os: inputs.os.split(','), node-version: inputs.node-version.split(',')}"
          result-encoded: json
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo '${{ steps.step-1.outputs.step-output}}'
          echo '${{ steps.step-2.outputs.step-output}}'
  node-matrix:
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).os}}
        node-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).node-version}}
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: node -v