name: Environment Variables

on: [push]

env:
  WF_LEVEL_ENV: Available for all jobs

jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      JOB_LEVEL_ENV: Available for all steps in this job
    steps:
      - name: Log ENV VAR
        run: echo $GITHUB_REF
      - name: logging by context
        run: echo '${{github.ref}}'
      - name: Adding env var
        run: |
          echo "RANDOM_NUMBER=$RANDOM" >> "$GITHUB_ENV"
          echo "TODAY_DATE=$(date)" >>"$GITHUB_ENV"
      - name: Adding multiline env var
        run: |
          DELIMETER = 1234
          echo "RANDOM_JOKE<<$DELIMETER" >> "$GITHUB_ENV"
          echo "Here is the joke: " >> "$GITHUB_ENV"
          curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
          echo "" >> "$GITHUB_ENV"
          echo "$DELIMETER" >>"$GITHUB_ENV"

      - name: Log custom ENV vars
        env:
          STEP_LEVEL_VAR: Available to step
          WF_LEVEL_ENV: In the step
        run: |
          echo '${{env.STEP_LEVEL_VAR}}'
          echo $STEP_LEVEL_VAR
          echo $WF_LEVEL_ENV
          echo $JOB_LEVEL_ENV
          echo $RANDOM_NUMBER
          echo $TODAY_DATE
          echo $RANDOM_JOKE