name: Manually Triggered

on:
  workflow_dispatch:
    inputs:
      input_name:
        description: This is input example
        type: string
        default: "Default value"
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF