name: Matrix

on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        node-version: [14,15,16]

        exclude:
          - os: ubuntu-latest
            node-version: 15
        
        include:
          - os: ubuntu-latest
            name: Lakshay
          - os: windows-latest
            node-version: 16
            name: Lakshay
    #   max-parallel: 3
    #   fail-fast: false
    runs-on: ${{ matrix.os}}
    steps:
      - run: node -v
      - run: echo '${{toJson(matrix)}}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: node -v