name: Schedule Stale

on:
  schedule:
    # mm hh day(month) month day(week)
    - cron: "0 7 * * *"  # Everyday at 7:00 am
    - cron: "0/5 * * * *" # Every 5 minutes from the 0th minute.

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hi there!"
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This is stale message" 
          days-before-stale: 1
          days-before-close: 5
