name: Working directory and shell

on: [push]

defaults:
  run:
    shell: bash
    # working-directory: /home/runner

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directories and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Changing working directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
        run:
          shell: pwsh
    steps:
      - name: Display working directories and list files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE  
      - name: Changing the shell
        shell: bash
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE