name: Working directory and shell

on: [push]

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directories and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display working directories and list files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE  